export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST"
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS"
export const SIGN_UP_ERROR = "SIGN_UP_ERROR"

export const LOG_IN_REQUEST = "LOG_IN_REQUEST"
export const LOG_IN_SUCCESS = "LOG_IN__SUCCESS"
export const LOG_IN_ERROR = "LOG_IN__ERROR"

export const LIST_ALL_POLL_REQUEST = "LIST_ALL_POLL_REQUEST"
export const LIST_ALL_POLL_SUCCESS = "LIST_ALL_POLL_SUCCESS"
export const LIST_ALL_POLL_ERROR = "LIST_ALL_POLL_ERROR"

export const VOTE_POLL_REQUEST = "VOTE_POLL_REQUEST"
export const VOTE_POLL_SUCCESS = "VOTE_POLL_SUCCESS"
export const VOTE_POLL_ERROR = "VOTE_POLL_ERROR"

export const ADD_POLL_REQUEST = "ADD_POLL_REQUEST"
export const ADD_POLL_SUCCESS = "ADD_POLL_SUCCESS"
export const ADD_POLL_ERROR = "ADD_POLL_ERROR"

export const VIEW_POLL_REQUEST = "VIEW_POLL_REQUEST"
export const VIEW_POLL_SUCCESS = "VIEW_POLL_SUCCESS"
export const VIEW_POLL_ERROR = "VIEW_POLL_ERROR"

export const UPDATE_POLL_REQUEST = "UPDATE_POLL_REQUEST"
export const UPDATE_POLL_SUCCESS = "UPDATE_POLL_SUCCESS"
export const UPDATE_POLL_ERROR =   "UPDATE_POLL_ERROR"

export const ADD_OPT_REQUEST = "ADD_OPT_REQUEST"
export const ADD_OPT_SUCCESS = "ADD_OPT_SUCCESS"
export const ADD_OPT_ERROR =   "ADD_OPT_ERROR"


export const DELETE_OPTION_REQUEST = "DELETE_OPTION_REQUEST"
export const DELETE_OPTION_SUCCESS = "DELETE_OPTION_SUCCESS"
export const DELETE_OPTION_ERROR =   "DELETE_OPTION_ERROR"

